apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: registry-pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: local-path-pvc
    namespace: default
    resourceVersion: "587771"
    uid: 4d1f5e87-2db0-48b5-8873-b41d688d2057
  hostPath:
    path: /mnt/usb/k3s-data/storage
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
