apiVersion: v1
kind: Namespace
metadata:
  name: image-registry
spec: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-registry
  name: image-registry
  namespace: image-registry
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: image-registry
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: image-registry
  name: image-registry
  namespace: image-registry
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: image-registry
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: image-registry
    spec:
      containers:
      - image: registry:latest
        imagePullPolicy: Always
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: registry-volume
        persistentVolumeClaim:
          claimName: local-path-pvc

